### ISSUE TITLE
Error occurred in cleanup job caused by dangling transitive references from `GitRepoMetrics`

### ISSUE THREAD

**Issue by dabico** [seart-group/ghs#72]
We've had an incident during cleanup:

```
gse-app  | 2023-05-12 14:21:27.334  WARN 1 --- [     GHSThread1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1451, SQLState: 23000
gse-app  | 2023-05-12 14:21:27.334 ERROR 1 --- [     GHSThread1] o.h.engine.jdbc.spi.SqlExceptionHelper   : Cannot delete or update a parent row: a foreign key constraint fails (`gse`.`repo_metrics`, CONSTRAINT `repo_metrics_ibfk_1` FOREIGN KEY (`repo_id`) REFERENCES `repo` (`id`))
gse-app  | 2023-05-12 14:21:27.344 ERROR 1 --- [     GHSThread1] usi.si.seart.job.CleanUpProjectsJob      : Exception occurred while deleting GitRepo [id=58131437, name=asahiocean/qr]!
gse-app  | 
gse-app  | javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
gse-app  | 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
gse-app  | 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181)
gse-app  | 	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1705)
gse-app  | 	at usi.si.seart.job.CleanUpProjectsJob.run(CleanUpProjectsJob.java:84)
gse-app  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gse-app  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
gse-app  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
gse-app  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
gse-app  | 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
gse-app  | 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
gse-app  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
gse-app  | 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
gse-app  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
gse-app  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
gse-app  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
gse-app  | 	at java.base/java.lang.Thread.run(Unknown Source)
gse-app  | Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
gse-app  | 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
gse-app  | 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
gse-app  | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
gse-app  | 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
gse-app  | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
gse-app  | 	at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:80)
gse-app  | 	at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:50)
gse-app  | 	at org.hibernate.hql.internal.ast.exec.DeleteExecutor.execute(DeleteExecutor.java:177)
gse-app  | 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:458)
gse-app  | 	at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:377)
gse-app  | 	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1478)
gse-app  | 	at org.hibernate.query.internal.AbstractProducedQuery.doExecuteUpdate(AbstractProducedQuery.java:1714)
gse-app  | 	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1696)
gse-app  | 	... 13 common frames omitted
gse-app  | Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`gse`.`repo_metrics`, CONSTRAINT `repo_metrics_ibfk_1` FOREIGN KEY (`repo_id`) REFERENCES `repo` (`id`))
gse-app  | 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
gse-app  | 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
gse-app  | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
gse-app  | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
gse-app  | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
gse-app  | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
gse-app  | 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
gse-app  | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
gse-app  | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
gse-app  | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
gse-app  | 	... 21 common frames omitted
gse-app  | 
gse-app  | 2023-05-12 14:21:27.345  INFO 1 --- [     GHSThread1] usi.si.seart.job.CleanUpProjectsJob      : Rolling back transaction...
gse-app  | 2023-05-12 14:21:27.365 ERROR 1 --- [     GHSThread1] .c.SchedulerConfig$SchedulerErrorHandler : Unhandled exception occurred while performing a scheduled job.
```

Take a look at this particular section of `CleanUpProjectsJob`:

https://github.com/seart-group/ghs/blob/107edc6f667fce6fdc814532c1608955d7de0299/src/main/java/usi/si/seart/job/CleanUpProjectsJob.java#L77-L99

As you can see, all the foreign key references to a repository are deleted prior to it being removed from the database. What you forgot to add here was the SQL statement that would also clear the rows from the `repo_metrics` junction table that match the ID of the repo being deleted. Please add the necessary update query that would delete entries from `GitRepoMetric` whose `repo_id` field matches the `:id`.

**Comment by AlbertCerfeda** [comment]
Alternatively, instead of deleting by creating a query manually we could delete the repository through its own `GitRepoService` method, and in theory any orphan `GitRepoLabels`/`GitRepoLanguage`/`GitRepoMetric` would get deleted aswell

**Comment by dabico** [comment]
Please take a look at the [commit comment](https://github.com/seart-group/ghs/commit/9ca183a1d488c5dd2669ab8790a7aaf9ae19ad31#commitcomment-113360339).

**Comment by dabico** [comment]
Please take a look at the [commit comment](https://github.com/seart-group/ghs/commit/e1fd1f5d21e831adb30cc163573db4e6622a84dc#commitcomment-113362708).
